Updated version 0.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -518,7 +518,7 @@ fi
 
 
 
-                      
+                       
                                       
                                                                                                                        
 
@@ -1251,6 +1251,18 @@ else
 fi
 
 
+echo $ac_n "checking whether to enable header compatibility mode""... $ac_c" 1>&6
+echo "configure:1256: checking whether to enable header compatibility mode" >&5
+if test "${HEADER_COMPAT}" != "yes"; then
+  HEADER_COMPAT="no";
+  echo "$ac_t""no" 1>&6
+else
+  HEADER_COMPAT="yes";
+  echo "$ac_t""yes" 1>&6
+fi
+
+
+
 if test "${CXX2}" = "" ; then
 	CXX2="no"
 fi
@@ -1274,7 +1286,7 @@ CXX_NAME=""
 
 if test "${CXX}" != "" ; then
   echo $ac_n "checking for compiler defined via CXX""... $ac_c" 1>&6
-echo "configure:1278: checking for compiler defined via CXX" >&5
+echo "configure:1290: checking for compiler defined via CXX" >&5
   if test -f "${CXX}" ; then
     echo "$ac_t""${CXX}" 1>&6
   else
@@ -1282,7 +1294,7 @@ echo "configure:1278: checking for compiler defined via CXX" >&5
     # Extract the first word of "${CXX}", so it can be a program name with args.
 set dummy ${CXX}; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1286: checking for $ac_word" >&5
+echo "configure:1298: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CXXPATH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1357,7 +1369,7 @@ EOF
 
           if test "${IS_GXX}" = "true" ; then
     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1361: checking compiler version" >&5
+echo "configure:1373: checking compiler version" >&5
     CXX_VERSION=`${CXX} --version`
     CXX_COMPILER_NAME="g++"
     VERSION_OUTPUT="g++ ${CXX_VERSION}"
@@ -1378,7 +1390,7 @@ echo "configure:1361: checking compiler version" >&5
 
     elif test "${OS}" = "IRIX" ; then
                     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1382: checking compiler version" >&5
+echo "configure:1394: checking compiler version" >&5
     CXX_VERSION_STRING=`${CXX} -n32 -version 2>&1 | egrep ersion`
     if test "${CXX_VERSION_STRING}" = "" ; then
       
@@ -1405,7 +1417,7 @@ echo "configure:1382: checking compiler version" >&5
 
     elif test "${OS}" = "Solaris" ; then
     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1409: checking compiler version" >&5
+echo "configure:1421: checking compiler version" >&5
     CXX_VERSION_STRING=`${CXX} -V 2>&1 | egrep CC:`
     CXX_VERSION=`${ECHO} ${CXX_VERSION_STRING} | ${TR} -d "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:" | ${TR} -s " " | ${CUT} -d\  -f2`
     
@@ -1434,7 +1446,7 @@ echo "configure:1409: checking compiler version" >&5
   fi
           
   echo $ac_n "checking standardized compiler name""... $ac_c" 1>&6
-echo "configure:1438: checking standardized compiler name" >&5
+echo "configure:1450: checking standardized compiler name" >&5
   if test "${CXX_VERSION_1}" != "" ; then
     _CXX_NAME="${_CXX_NAME}-${CXX_VERSION_1}"
     if test "${CXX_VERSION_2}" != "" ; then
@@ -1479,7 +1491,7 @@ else
     # Extract the first word of "${CXXCAND}", so it can be a program name with args.
 set dummy ${CXXCAND}; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1483: checking for $ac_word" >&5
+echo "configure:1495: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CXXPATH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1545,7 +1557,7 @@ EOF
 
           if test "${IS_GXX}" = "true" ; then
     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1549: checking compiler version" >&5
+echo "configure:1561: checking compiler version" >&5
     CXX_VERSION=`${CXXCAND} --version`
     CXX_COMPILER_NAME="g++"
     VERSION_OUTPUT="g++ ${CXX_VERSION}"
@@ -1566,7 +1578,7 @@ echo "configure:1549: checking compiler version" >&5
 
     elif test "${OS}" = "IRIX" ; then
                     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1570: checking compiler version" >&5
+echo "configure:1582: checking compiler version" >&5
     CXX_VERSION_STRING=`${CXXCAND} -n32 -version 2>&1 | egrep ersion`
     if test "${CXX_VERSION_STRING}" = "" ; then
       
@@ -1593,7 +1605,7 @@ echo "configure:1570: checking compiler version" >&5
 
     elif test "${OS}" = "Solaris" ; then
     echo $ac_n "checking compiler version""... $ac_c" 1>&6
-echo "configure:1597: checking compiler version" >&5
+echo "configure:1609: checking compiler version" >&5
     CXX_VERSION_STRING=`${CXXCAND} -V 2>&1 | egrep CC:`
     CXX_VERSION=`${ECHO} ${CXX_VERSION_STRING} | ${TR} -d "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:" | ${TR} -s " " | ${CUT} -d\  -f2`
     
@@ -1622,7 +1634,7 @@ echo "configure:1597: checking compiler version" >&5
   fi
           
   echo $ac_n "checking standardized compiler name""... $ac_c" 1>&6
-echo "configure:1626: checking standardized compiler name" >&5
+echo "configure:1638: checking standardized compiler name" >&5
   if test "${CXX_VERSION_1}" != "" ; then
     _CXX_NAME="${_CXX_NAME}-${CXX_VERSION_1}"
     if test "${CXX_VERSION_2}" != "" ; then
@@ -1707,7 +1719,7 @@ fi
 
 
 echo $ac_n "checking compiler flags to build ${LINKING_MODE} libraries with ${CXX_STD_NAME} on ${OS}""... $ac_c" 1>&6
-echo "configure:1711: checking compiler flags to build ${LINKING_MODE} libraries with ${CXX_STD_NAME} on ${OS}" >&5
+echo "configure:1723: checking compiler flags to build ${LINKING_MODE} libraries with ${CXX_STD_NAME} on ${OS}" >&5
 tableline=`grep "${OS}" confdir/flagtable | grep "${LINKING_MODE}" | grep " ${CXX_STD_NAME}" | grep ${CXX2}`
 CXX2_COMMAND=`${ECHO} ${tableline} | cut -d, -f5`
 CXX_COMP_FLAGS=`${ECHO} ${tableline} | cut -d, -f6`
@@ -1773,20 +1785,37 @@ else
 fi
 
 echo $ac_n "checking LEDA Installation""... $ac_c" 1>&6
-echo "configure:1777: checking LEDA Installation" >&5
+echo "configure:1789: checking LEDA Installation" >&5
+_found_ledaroot="false"
 if test -f "${LEDAROOT}/incl/LEDA/basic.h"; then
-  echo "$ac_t""found" 1>&6
+  echo "$ac_t""found, v4.5 or older" 1>&6
   LEDA_INCL_PATH="${LEDAROOT}/incl"
+  _found_ledaroot="true"
+else
+    if test -f "${LEDAROOT}/incl/LEDA/system/basic.h"; then
+      echo "$ac_t""found, v5.0 or newer" 1>&6
+      LEDA_INCL_PATH="${LEDAROOT}/incl"
+
+      if test "${HEADER_COMPAT}" = "yes" && test -f "${LEDAROOT}/incl_old/LEDA/basic.h"; then
+        echo "$ac_t""enabling header compatibility mode..." 1>&6
+        LEDA_INCL_PATH="$LEDA_INCL_PATH ${LEDAROOT}/incl_old"
+      fi
+      _found_ledaroot="true"
+    else
+      { echo "configure: error: LEDAROOT not defined!" 1>&2; exit 1; }
+    fi
+fi
+
+if test "$_found_ledaroot" = "true"; then 
   if test "${LINKING_MODE}" = "shared" ; then
     LEDA_LIB_PATH="${LEDAROOT}"
   else
     LEDA_LIB_PATH="${LEDAROOT}/static"
   fi
-else
-  { echo "configure: error: LEDAROOT not defined!" 1>&2; exit 1; }
 fi
+
 echo $ac_n "checking how to run the C++ preprocessor""... $ac_c" 1>&6
-echo "configure:1790: checking how to run the C++ preprocessor" >&5
+echo "configure:1819: checking how to run the C++ preprocessor" >&5
 if test -z "$CXXCPP"; then
 if eval "test \"`echo '$''{'ac_cv_prog_CXXCPP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1799,12 +1828,12 @@ ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftes
 cross_compiling=$ac_cv_prog_cxx_cross
   CXXCPP="${CXX-g++} -E"
   cat > conftest.$ac_ext <<EOF
-#line 1803 "configure"
+#line 1832 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1808: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1837: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1830,17 +1859,17 @@ echo "$ac_t""$CXXCPP" 1>&6
 
 ac_safe=`echo "assert.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for assert.h""... $ac_c" 1>&6
-echo "configure:1834: checking for assert.h" >&5
+echo "configure:1863: checking for assert.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1839 "configure"
+#line 1868 "configure"
 #include "confdefs.h"
 #include <assert.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1844: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1873: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1866,7 +1895,7 @@ fi
 LEP_COMP_FLAGS=""   LEP_LIB_FLAGS=""    LEP_LINK_FLAGS=""   LEP_LIBS=""         		    
 
 echo $ac_n "checking Additional compiler and linker flags and libraries""... $ac_c" 1>&6
-echo "configure:1870: checking Additional compiler and linker flags and libraries" >&5
+echo "configure:1899: checking Additional compiler and linker flags and libraries" >&5
 tableline=`grep "${OS}" confdir/userflagtable | grep ${LINKING_MODE} | grep " ${CXX_STD_NAME}"`
 
 LEP_COMP_FLAGS=`${ECHO} ${tableline} | cut -d, -f4`
@@ -1896,12 +1925,12 @@ echo "$ac_t""done" 1>&6
 
 
 echo $ac_n "checking for ANSI C header files""... $ac_c" 1>&6
-echo "configure:1900: checking for ANSI C header files" >&5
+echo "configure:1929: checking for ANSI C header files" >&5
 if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1905 "configure"
+#line 1934 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -1909,7 +1938,7 @@ else
 #include <float.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1913: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1942: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1926,7 +1955,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1930 "configure"
+#line 1959 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -1944,7 +1973,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1948 "configure"
+#line 1977 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -1965,7 +1994,7 @@ if test "$cross_compiling" = yes; then
   :
 else
   cat > conftest.$ac_ext <<EOF
-#line 1969 "configure"
+#line 1998 "configure"
 #include "confdefs.h"
 #ifdef __cplusplus
 extern "C" void exit(int);
@@ -1979,7 +2008,7 @@ if (XOR (islower (i), ISLOWER (i)) || toupper (i) != TOUPPER (i)) exit(2);
 exit (0); }
 
 EOF
-if { (eval echo configure:1983: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2012: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -2003,12 +2032,12 @@ EOF
 fi
 
 echo $ac_n "checking for size_t""... $ac_c" 1>&6
-echo "configure:2007: checking for size_t" >&5
+echo "configure:2036: checking for size_t" >&5
 if eval "test \"`echo '$''{'ac_cv_type_size_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2012 "configure"
+#line 2041 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -2036,12 +2065,12 @@ EOF
 fi
 
 echo $ac_n "checking whether time.h and sys/time.h may both be included""... $ac_c" 1>&6
-echo "configure:2040: checking whether time.h and sys/time.h may both be included" >&5
+echo "configure:2069: checking whether time.h and sys/time.h may both be included" >&5
 if eval "test \"`echo '$''{'ac_cv_header_time'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2045 "configure"
+#line 2074 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/time.h>
@@ -2050,7 +2079,7 @@ int main() {
 struct tm *tp;
 ; return 0; }
 EOF
-if { (eval echo configure:2054: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2083: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_header_time=yes
 else
@@ -2076,12 +2105,12 @@ fi
 for ac_func in strstr
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:2080: checking for $ac_func" >&5
+echo "configure:2109: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2085 "configure"
+#line 2114 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -2107,7 +2136,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:2111: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2140: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -2138,7 +2167,7 @@ BINFMT="${BINFMT}-${CXX_NAME}"
 # Extract the first word of "dirname", so it can be a program name with args.
 set dummy dirname; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2142: checking for $ac_word" >&5
+echo "configure:2171: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_DIRNAME'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2172,7 +2201,7 @@ else
 fi
 
 echo $ac_n "checking for ${CXX_STD_NAME} header files...""... $ac_c" 1>&6
-echo "configure:2176: checking for ${CXX_STD_NAME} header files..." >&5
+echo "configure:2205: checking for ${CXX_STD_NAME} header files..." >&5
 ${ECHO} "#include <iostream.h>" >/tmp/$$.test.C
 LINES=`${CXX} -E /tmp/$$.test.C | egrep /iostream.h\"`
 ${RM} /tmp/$$.test.C
@@ -2314,6 +2343,7 @@ s%@CXX_NAME@%$CXX_NAME%g
 s%@CXX_STD_NAME@%$CXX_STD_NAME%g
 s%@CXX_FOUND_LIST@%$CXX_FOUND_LIST%g
 s%@LINKING_MODE@%$LINKING_MODE%g
+s%@HEADER_COMPAT@%$HEADER_COMPAT%g
 s%@LIB_SUFFIX@%$LIB_SUFFIX%g
 s%@OSMAJOR@%$OSMAJOR%g
 s%@OS@%$OS%g
@@ -2515,6 +2545,10 @@ test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
   ${ECHO} "LEDA root dir        :     LEDAROOT = '${LEDAROOT}'" >&5
 
   
+  ${ECHO} "Header compatibility :     HEADER_COMPAT = '${HEADER_COMPAT}'" 1>&6
+  ${ECHO} "Header compatibility :     HEADER_COMPAT = '${HEADER_COMPAT}'" >&5
+
+  
   ${ECHO} "" 1>&6
   ${ECHO} "" >&5
 
@@ -2543,8 +2577,8 @@ test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
   ${ECHO} "" >&5
 
   
-  ${ECHO} "  CXX=<compiler> CXX2=<defsetting> CXX_FLAGS=<flags> LINKING_MODE=<linkmode> LEDAROOT=<ledaroot> configure" 1>&6
-  ${ECHO} "  CXX=<compiler> CXX2=<defsetting> CXX_FLAGS=<flags> LINKING_MODE=<linkmode> LEDAROOT=<ledaroot> configure" >&5
+  ${ECHO} "  CXX=<compiler> CXX2=<defsetting> CXX_FLAGS=<flags> LINKING_MODE=<linkmode> LEDAROOT=<ledaroot> HEADER_COMPAT=<boolean> configure" 1>&6
+  ${ECHO} "  CXX=<compiler> CXX2=<defsetting> CXX_FLAGS=<flags> LINKING_MODE=<linkmode> LEDAROOT=<ledaroot> HEADER_COMPAT=<boolean> configure" >&5
 
   
   ${ECHO} "" 1>&6
@@ -2571,12 +2605,16 @@ test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
   ${ECHO} "  <flags>      are compiler flags of <compiler>," >&5
 
   
-  ${ECHO} "  <linkmode>   is out of {'static','shared'} and" 1>&6
-  ${ECHO} "  <linkmode>   is out of {'static','shared'} and" >&5
+  ${ECHO} "  <linkmode>   is out of {'static','shared'}," 1>&6
+  ${ECHO} "  <linkmode>   is out of {'static','shared'}," >&5
 
   
-  ${ECHO} "  <ledaroot>   specifies the LEDA installation directory." 1>&6
-  ${ECHO} "  <ledaroot>   specifies the LEDA installation directory." >&5
+  ${ECHO} "  <ledaroot>   specifies the LEDA installation directory and" 1>&6
+  ${ECHO} "  <ledaroot>   specifies the LEDA installation directory and" >&5
+
+  
+  ${ECHO} "  <boolean>    is out of {'yes','no'}." 1>&6
+  ${ECHO} "  <boolean>    is out of {'yes','no'}." >&5
 
   
   ${ECHO} "" 1>&6
